# Generated by Django 5.1.1 on 2024-10-30 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_payment_order_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='razer_payment_id',
            new_name='razorpay_payment_id',
        ),
    ]
